/*
* Automatically generated by 'ng g ng-alain:plugin icon'
*/

import {
  ArrowDownOutline,
  CopyrightOutline,
  DeleteTwoTone,
  DragOutline,
  EditTwoTone,
  FullscreenExitOutline,
  FullscreenOutline,
  LockOutline,
  LockTwoTone,
  LogoutOutline,
  PlayCircleOutline,
  PlayCircleTwoTone,
  PoweroffOutline,
  QuestionOutline,
  SettingOutline,
  StopTwoTone,
  ThunderboltOutline,
  ThunderboltTwoTone,
  ToolOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  ArrowDownOutline,
  CopyrightOutline,
  DeleteTwoTone,
  DragOutline,
  EditTwoTone,
  FullscreenExitOutline,
  FullscreenOutline,
  LockOutline,
  LockTwoTone,
  LogoutOutline,
  PlayCircleOutline,
  PlayCircleTwoTone,
  PoweroffOutline,
  QuestionOutline,
  SettingOutline,
  StopTwoTone,
  ThunderboltOutline,
  ThunderboltTwoTone,
  ToolOutline,
  UserOutline
];
