/*
* Automatically generated by 'ng g ng-alain:plugin icon'
*/

import {
  ArrowDownOutline,
  CopyrightOutline,
  DragOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  LockOutline,
  LogoutOutline,
  PlayCircleOutline,
  SettingOutline,
  ToolOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  ArrowDownOutline,
  CopyrightOutline,
  DragOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  LockOutline,
  LogoutOutline,
  PlayCircleOutline,
  SettingOutline,
  ToolOutline,
  UserOutline
];
